{
    'name': 'Education Management',
    'version': '1.0',
    'summary': 'Education Management',
    'sequence': 1,
    'description': 'Demo',
    'category': 'other',
    'author': 'Tran Quy',
    'website': '',
    'license': '',
    'depends': ['hr',
                ],
    'data': [
        'security/ir.model.access.csv',
        'views/subjects_views.xml',
        'views/schedule_learn.xml',
        'views/manage_class_view.xml',
        'views/location_included_view.xml',
        'views/classroom_view.xml',
        'views/res_hr_employee.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
}